apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'flask-app'
        metrics_path: /metrics/prometheus
        static_configs:
          - targets: ['<flask-app-ip>:<flask-app-port>']
